name: pong_score
description: App score raking for table tennis
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # firebase: ^7.2.1
  # firebase_core: ^0.4.4+3
  # Add the dependency for the FlutterFire plugin for Google Analytics
  device_preview: 0.4.4
  # firebase_analytics: ^5.0.11
  # firebase_web: ^5.0.9
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.4+2
  sealed_unions: ^3.0.2+2
  font_awesome_flutter: ^8.8.1
  flutter_cupertino_localizations: ^1.0.1
  responsive_builder: ^0.1.6

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.16.0

  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  polygon_clipper: ^1.0.2

  # DDD packages related

  flutter_svg: ^0.17.4

  dartz: ^0.9.0
  freezed_annotation: ^0.7.1
  uuid: ^2.0.4
  auto_route: ^0.4.5
  get_it: ^4.0.2
  meta: ^1.1.8
  google_sign_in: ^4.1.1
  injectable: ^0.3.0
  flushbar: ^1.10.0
  json_annotation: ^3.0.1
  styled_widget: ^0.2.1+2
  flutter_hooks: ^0.9.0
  time: ^1.3.0
  kt_dart: ^0.7.0
  rxdart: ^0.24.0
  reorderables: ^0.3.2
  provider: ^4.0.5+1
  implicitly_animated_reorderable_list: ^0.1.10
  flutter_slidable: ^0.5.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1.1
  build_runner:
  freezed: ^0.10.7
  auto_route_generator: ^0.4.7
  injectable_generator: ^0.3.4
  json_serializable: ^3.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/domain/core/lang/en.json
    - lib/domain/core/lang/es.json
    - images/header.png
    - images/login_logo_light.png
    - images/header-slide.png
    - images/vector.png
    - images/vectors/vector.svg
  fonts:
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
        - asset: fonts/Orbitron-Medium.ttf
        - asset: fonts/Orbitron-Bold.ttf
        - asset: fonts/Orbitron-Black.ttf
          weight: 700
